{{- if and (not .Values.secrets.existingSecret) (or .Values.secrets.jwtSecret .Values.secrets.tokenEncKey .Values.secrets.bootstrapEmail) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tabularium.fullname" . }}
  labels:
    {{- include "tabularium.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.tokenEncKey }}
  TOKEN_ENC_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.bootstrapEmail }}
  BOOTSTRAP_EMAIL: {{ . | quote }}
  {{- end }}
{{- end }}
