export { registry } from './registry'
export { bus } from './events'
export { initPlugins, __setLoaderForTests, __clearLoadedForTests } from './loader'
export { listContributions, __clearContributions } from './contributions'
export { listRoutes, __clearRoutes } from './route-collector'
export { buildHost } from './host'
export { resolvePluginLoader, listKnownPluginIds } from './resolver'
